### ISSUE TITLE
Can't launch 1.0.6

### ISSUE THREAD

**Issue by eliasacab** [nekupaw/gemini-desktop#10]
Thanks for the work you've put into the helpful tool! Unfortunately the latest version is giving this error message when I try to launch it:

![Screenshot 2024-10-21 075704](https://github.com/user-attachments/assets/b3861437-5607-4281-8226-df622f6070ee)

**Comment by nekupaw** [comment]
sorry, I compiled and uploaded it again, could you test if it works?

**Comment by eliasacab** [comment]
It's working now! Thanks again.
