### ISSUE TITLE
Feature Request:  Start Minimized option

### ISSUE THREAD

**Issue by ninjaeon** [nekupaw/gemini-desktop#12]
I have Gemini Desktop opening at startup so that it's ready to go in my system tray.  It would be useful if it had a "start minimized" option.

Thank you for this!

**Comment by nekupaw** [comment]
Sure: [Windows-Setup (v1.0.7)](https://github.com/nekupaw/gemini-desktop/releases/download/1.0.7/Gemini-Desktop.Setup.1.0.7.exe)

**Comment by ninjaeon** [comment]
Thank you very much!
