### ISSUE TITLE
REQUEST: Enable always on top

### ISSUE THREAD

**Issue by johrad** [nekupaw/gemini-desktop#3]
Would it be possible to implement an "always on top" feature with a Ctrl+G hotkey to dismiss? This would prevent the window from disappearing unintentionally during other tasks.

**Comment by nekupaw** [comment]
I could try implementing it today and publishing a new release.
Just give me some time ^^

**Comment by nekupaw** [comment]
**So, just released an update which should fix your problem.**
[Gemini Client for Windows (Setup)](https://github.com/nekupaw/gemini-desktop/releases/download/1.0.3/Gemini-Desktop.Setup.1.0.3.exe)
If you have any suggestions for improvement, just let me know ;3


![image](https://github.com/user-attachments/assets/ffa93bd1-c3b1-4d95-bcbb-0af6b47a23f4)

**Comment by nekupaw** [comment]
**So, just released an update which should fix your problem.**
[Version 1.0.3  (Setup)](https://github.com/nekupaw/gemini-desktop/releases/download/1.0.3/Gemini-Desktop.Setup.1.0.3.exe)

If you have any suggestions for improvement, just let me know ;3

![image](https://github.com/user-attachments/assets/ffa93bd1-c3b1-4d95-bcbb-0af6b47a23f4)

**Comment by johrad** [comment]
Excellent! works well, thank you for your efforts :)
