### ISSUE TITLE
Added Support for ARM64 Macs

### ISSUE THREAD

**Issue by anongecko** [nekupaw/gemini-desktop#4]
First of all, thanks for creating this!

I recently downloaded the Windows version and was able to successfully modify the source code to work on my ARM64 (M1) Mac. I've created a .dmg file for easy installation.

I was wondering if you would be interested in adding the .dmg to your releases for other Mac users? I'm unable to provide the full modified code or the .dmg here because of file size limitations, but I'm happy upload both if you are interested.

Thanks again for your work on this project!

**Comment by nekupaw** [comment]
Hey, feel free to send me the revised source code. I'll compile it myself (for security reasons) and add it to the repository so everyone else can access it.
If it doesn't work here because of the size of the files, just send me a Google Drive or Dropbox link, depending on your preference.

**Comment by anongecko** [comment]
Absolutely! I've also made some changes based on personal preference, and that may be helpful for mac users.
- Made it appear on the dock
- Resizable, opens in center of the page rather than bottom right (but can still be toggled with Command+g)
- Changed icon to be a .icns fitting mac standards

Basically all of the changes were made to index.js, but you can check it out. Thanks again for making this!

Here is a drive link (uncompressed):
https://drive.google.com/drive/folders/1sjirgJvxWgOCR0zPB91VULqXJkbARjnA?usp=sharing

**Comment by nekupaw** [comment]
I'm just realizing now that I'm not able to compile it myself because I'm working on a Windows machine.
Just send me the dmg and I'll upload it that way.

**Comment by anongecko** [comment]
Haha, no worries.

Here's a link to the .dmg:
https://drive.google.com/file/d/1sUAObFA2GDtCNgVphTfvjKpRdFJh8i3z/view?usp=sharing 

It was compiled from the exact source code in the link above.

**Comment by nekupaw** [comment]
Yay, thanks for your cooperation.
I have attached your version to the [release](https://github.com/nekupaw/gemini-desktop/releases/tag/1.0.3).

**Comment by nekupaw** [comment]
@anongecko would it be possible for you to compile future updates for mac as well?I also would add you as a collaborator

**Comment by anongecko** [comment]
Never saw this, sorry. I can if you still are interested in this project. I plan to rebuild it later today, as I still use it daily. Thanks.

**Comment by nekupaw** [comment]
ayy thanks :)

**Comment by anongecko** [comment]
I rebuilt the application with Tauri in Rust. Do you still want to add it to releases, or should I make it its own repo?

**Comment by nekupaw** [comment]
I don't want to maintain the repo anymore, so I would like to add you as a collaborator and remove myself from the repo if that's okay fou you?

**Comment by anongecko** [comment]
Yep, that works for me. Sorry for the delayed reply. Do you have any preference if I continue with the electron releases vs the rust version I made?

**Comment by nekupaw** [comment]
oh sorry, didn't see the message. You can decide yourself how you want to continue.
I have now invited you as a collaborator.
