### ISSUE TITLE
Change/Disable Keyboard Shortcut

### ISSUE THREAD

**Issue by eliasacab** [nekupaw/gemini-desktop#6]
Thanks for this great little app, it's so useful! Wondering if it's possible to add an option to either change or disable the keyboard shortcut Ctrl+G? Certain programs (Adobe specifically) use this shortcut for grouping objects, a very common task when designing, and Gemini pops up and overrides the command. Thanks!

**Comment by nekupaw** [comment]
Setting up a shortcut yourself should be a given, maybe I'll implement it tomorrow. Just give me some time :3

**Comment by nekupaw** [comment]
so u know that I haven't forgotten u:
![image](https://github.com/user-attachments/assets/43d6977c-0ed7-4f07-a32f-adbd51def9ea)

**Comment by eliasacab** [comment]
> but it will still take some patience
Sweet! Can't wait :)

**Comment by nekupaw** [comment]
Sooo, the feature to activate the mic with a shortcut doesn't work yet, but so you don't have to wait any longer, here's an update: [Windows Setup (v1.0.5)](https://github.com/nekupaw/gemini-desktop/releases/download/1.0.5/Gemini-Desktop.Setup.1.0.5.exe)
