### ISSUE TITLE
[FR] Can we have margin-bottom on the pop-up?

### ISSUE THREAD

**Issue by hoangnhan2ka3** [nekupaw/gemini-desktop#7]
![image](https://github.com/user-attachments/assets/ebb61aa6-1791-4e89-b0e7-4d77bbe11c18)

I'm using Windows 11.

Anyway, very nice and useful app 🎉

**Comment by nekupaw** [comment]
hmm, I think I have an idea how I could fix it. There is actually a margin at the bottom, but it's quite possible that it doesn't work on every screen. Just give me some patience

**Comment by nekupaw** [comment]
fixed: [Windows Setup (v1.0.5)](https://github.com/nekupaw/gemini-desktop/releases/download/1.0.5/Gemini-Desktop.Setup.1.0.5.exe)
