### ISSUE TITLE
Is there a way to move to 2nd/3rd monitor?

### ISSUE THREAD

**Issue by deezlici0us** [nekupaw/gemini-desktop#8]
Hi,
Thanks for this nice little app! Would use it way more if there would be a way to move it to one of my secondary monitors to avoid clogging.
Cheers\\

**Comment by nekupaw** [comment]
I will try to implement it, but it may take some time

**Comment by rajmondx** [comment]
I would love that feature too. I imagine its easier to just implement a "window mode" and allow the user to drag it wherever he wants to have it.

**Comment by nekupaw** [comment]
fixed: https://github.com/nekupaw/gemini-desktop/releases/download/1.0.6/Gemini-Desktop.Setup.1.0.6.exe
